-- Demo venues for development.
-- Replace 00000000-0000-0000-0000-000000000000 with a real auth.users.id,
-- or create a temporary auth user with that id before running this seed.
-- This block skips safely when the placeholder user does not exist.

do $$
declare
  demo_user uuid := '00000000-0000-0000-0000-000000000000';
begin
  if not exists (select 1 from auth.users where id = demo_user) then
    raise notice 'Skipping demo venues: placeholder auth.users id % does not exist.', demo_user;
    return;
  end if;

  insert into public.venues (
    id,
    name,
    description,
    address,
    city,
    country,
    lat,
    lng,
    venue_type,
    capacity_estimate,
    is_free_entry,
    indoor_outdoor,
    big_screen,
    food_available,
    family_friendly,
    screens_all_matches,
    photo_url,
    status,
    approved_by,
    approved_at,
    rejected_by,
    rejected_at,
    rejection_note,
    hidden_reason,
    created_by
  )
  values
    (
      '11111111-1111-4111-8111-111111111111',
      'Zocalo Fan Plaza',
      'Open-air downtown watch party space with a large LED screen, local food stalls, and family seating.',
      'Plaza de la Constitucion',
      'Mexico City',
      'Mexico',
      19.4326,
      -99.1332,
      'public_square',
      12000,
      true,
      'outdoor',
      true,
      true,
      true,
      true,
      null,
      'approved',
      demo_user,
      now(),
      null,
      null,
      null,
      null,
      demo_user
    ),
    (
      '22222222-2222-4222-8222-222222222222',
      'Harbourfront Match Garden',
      'Waterfront fan zone near transit with covered seating, food trucks, and replay screens.',
      '235 Queens Quay W',
      'Toronto',
      'Canada',
      43.6389,
      -79.3839,
      'fan_zone',
      3500,
      true,
      'both',
      true,
      true,
      true,
      true,
      null,
      'approved',
      demo_user,
      now(),
      null,
      null,
      null,
      null,
      demo_user
    ),
    (
      '33333333-3333-4333-8333-333333333333',
      'Pioneer Square Football Hall',
      'Indoor bar screening every late kickoff with reserved tables and a standing-room fan section.',
      '109 Yesler Way',
      'Seattle',
      'United States',
      47.6019,
      -122.3338,
      'pub_bar',
      280,
      false,
      'indoor',
      true,
      true,
      false,
      true,
      null,
      'approved',
      demo_user,
      now(),
      null,
      null,
      null,
      null,
      demo_user
    ),
    (
      '44444444-4444-4444-8444-444444444444',
      'Gastown Cup Corner',
      'Pending community listing for a casual indoor screening room with brunch service.',
      '312 Water St',
      'Vancouver',
      'Canada',
      49.2835,
      -123.1066,
      'restaurant',
      120,
      false,
      'indoor',
      true,
      true,
      true,
      false,
      null,
      'pending',
      null,
      null,
      null,
      null,
      null,
      null,
      demo_user
    ),
    (
      '55555555-5555-4555-8555-555555555555',
      'East Rutherford Tailgate Screen',
      'Pending outdoor match-day listing close to regional rail and shuttle pickup.',
      '1 MetLife Stadium Dr',
      'East Rutherford',
      'United States',
      40.8135,
      -74.0745,
      'fan_zone',
      800,
      true,
      'outdoor',
      true,
      true,
      false,
      false,
      null,
      'pending',
      null,
      null,
      null,
      null,
      null,
      null,
      demo_user
    ),
    (
      '66666666-6666-4666-8666-666666666666',
      'Inactive Midtown Watch Listing',
      'Rejected sample venue kept for moderation UI testing.',
      '10 Peachtree St NW',
      'Atlanta',
      'United States',
      33.7550,
      -84.3900,
      'other',
      60,
      false,
      'indoor',
      false,
      false,
      false,
      false,
      null,
      'rejected',
      null,
      null,
      demo_user,
      now(),
      'Venue could not be verified.',
      'Demo rejected record',
      demo_user
    )
  on conflict (id) do update
  set
    name = excluded.name,
    description = excluded.description,
    address = excluded.address,
    city = excluded.city,
    country = excluded.country,
    lat = excluded.lat,
    lng = excluded.lng,
    venue_type = excluded.venue_type,
    capacity_estimate = excluded.capacity_estimate,
    is_free_entry = excluded.is_free_entry,
    indoor_outdoor = excluded.indoor_outdoor,
    big_screen = excluded.big_screen,
    food_available = excluded.food_available,
    family_friendly = excluded.family_friendly,
    screens_all_matches = excluded.screens_all_matches,
    photo_url = excluded.photo_url,
    status = excluded.status,
    approved_by = excluded.approved_by,
    approved_at = excluded.approved_at,
    rejected_by = excluded.rejected_by,
    rejected_at = excluded.rejected_at,
    rejection_note = excluded.rejection_note,
    hidden_reason = excluded.hidden_reason;
end $$;
