-- World Cup 2026 screening locations schema.
-- Designed for Supabase Postgres 15+ and safe to re-run where Postgres allows
-- IF NOT EXISTS / CREATE OR REPLACE semantics. RLS policies and triggers are
-- dropped before recreation so policy edits are repeatable.

create extension if not exists pgcrypto with schema extensions;

create table if not exists public.teams (
  code text primary key,
  name text not null,
  group_letter text not null,
  flag_emoji text not null,
  constraint teams_group_letter_check check (group_letter ~ '^[A-L]$')
);

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default '',
  favorite_team text null references public.teams(code) on update cascade on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade
);

create table if not exists public.matches (
  id integer generated by default as identity primary key,
  match_number integer not null unique,
  stage text not null,
  home_team text null references public.teams(code) on update cascade on delete restrict,
  away_team text null references public.teams(code) on update cascade on delete restrict,
  kickoff_utc timestamptz not null,
  stadium text not null,
  city text not null,
  constraint matches_stage_check check (stage in ('group', 'r32', 'r16', 'qf', 'sf', 'third', 'final')),
  constraint matches_distinct_teams_check check (
    home_team is null
    or away_team is null
    or home_team <> away_team
  )
);

create table if not exists public.venues (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  description text not null,
  address text not null,
  city text not null,
  country text not null,
  lat double precision not null,
  lng double precision not null,
  venue_type text not null,
  capacity_estimate integer null,
  is_free_entry boolean not null default false,
  indoor_outdoor text not null,
  big_screen boolean not null default true,
  food_available boolean not null default false,
  family_friendly boolean not null default false,
  screens_all_matches boolean not null default true,
  photo_url text null,
  status text not null default 'pending',
  approved_by uuid null,
  approved_at timestamptz null,
  rejected_by uuid null,
  rejected_at timestamptz null,
  rejection_note text null,
  hidden_reason text null,
  created_by uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint venues_venue_type_check check (venue_type in ('fan_zone', 'pub_bar', 'restaurant', 'public_square', 'other')),
  constraint venues_indoor_outdoor_check check (indoor_outdoor in ('indoor', 'outdoor', 'both')),
  constraint venues_status_check check (status in ('pending', 'approved', 'rejected')),
  constraint venues_capacity_nonnegative_check check (capacity_estimate is null or capacity_estimate >= 0),
  constraint venues_lat_check check (lat between -90 and 90),
  constraint venues_lng_check check (lng between -180 and 180)
);

create table if not exists public.venue_matches (
  venue_id uuid not null references public.venues(id) on delete cascade,
  match_id integer not null references public.matches(id) on delete cascade,
  primary key (venue_id, match_id)
);

create table if not exists public.votes (
  venue_id uuid not null references public.venues(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (venue_id, user_id)
);

create table if not exists public.reports (
  id uuid primary key,
  venue_id uuid not null references public.venues(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  reason text not null,
  details text not null default '',
  status text not null default 'open',
  created_at timestamptz not null default now(),
  constraint reports_reason_check check (reason in ('outdated', 'wrong_info', 'closed', 'inappropriate', 'other')),
  constraint reports_status_check check (status in ('open', 'resolved'))
);

-- One *open* report per user per venue; users may report again after a
-- moderator resolves their earlier report.
create unique index if not exists reports_open_venue_user_unique
  on public.reports (venue_id, user_id)
  where status = 'open';

create index if not exists venues_status_country_city_idx on public.venues (status, country, city);
create index if not exists venues_status_venue_type_idx on public.venues (status, venue_type);
create index if not exists venues_created_by_status_idx on public.venues (created_by, status);
create index if not exists venues_status_lat_lng_idx on public.venues (status, lat, lng);
create index if not exists reports_status_venue_id_idx on public.reports (status, venue_id);
create index if not exists votes_venue_id_idx on public.votes (venue_id);
create index if not exists matches_kickoff_utc_idx on public.matches (kickoff_utc);

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.admin_users
    where user_id = auth.uid()
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to authenticated;
grant execute on function public.is_admin() to service_role;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.handle_new_user_profile()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, display_name)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'display_name', new.raw_user_meta_data ->> 'full_name', '')
  )
  on conflict (id) do nothing;

  return new;
end;
$$;

create or replace function public.enforce_venue_insert_limits()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  -- Non-admins cannot seed moderation metadata on insert.
  if not public.is_admin() then
    new.approved_by := null;
    new.approved_at := null;
    new.rejected_by := null;
    new.rejected_at := null;
    new.rejection_note := null;
    new.hidden_reason := null;
  end if;

  if not public.is_admin()
     and new.status = 'pending'
     and (
       select count(*)
       from public.venues
       where created_by = new.created_by
         and status = 'pending'
     ) >= 3 then
    raise exception 'pending submission limit reached';
  end if;

  return new;
end;
$$;

create or replace function public.enforce_venue_update_rules()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  new.updated_at = now();

  if not public.is_admin() and (
    new.status is distinct from old.status
    or new.created_by is distinct from old.created_by
    or new.approved_by is distinct from old.approved_by
    or new.approved_at is distinct from old.approved_at
    or new.rejected_by is distinct from old.rejected_by
    or new.rejected_at is distinct from old.rejected_at
    or new.rejection_note is distinct from old.rejection_note
    or new.hidden_reason is distinct from old.hidden_reason
  ) then
    raise exception 'only admins can change moderation fields';
  end if;

  return new;
end;
$$;

create or replace function public.enforce_report_insert_limits()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not public.is_admin()
     and new.status = 'open'
     and (
       select count(*)
       from public.reports
       where user_id = new.user_id
         and status = 'open'
     ) >= 10 then
    raise exception 'open report limit reached';
  end if;

  return new;
end;
$$;

drop trigger if exists set_profiles_updated_at on public.profiles;
create trigger set_profiles_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

drop trigger if exists on_auth_user_created_create_profile on auth.users;
create trigger on_auth_user_created_create_profile
after insert on auth.users
for each row execute function public.handle_new_user_profile();

drop trigger if exists enforce_venue_insert_limits on public.venues;
create trigger enforce_venue_insert_limits
before insert on public.venues
for each row execute function public.enforce_venue_insert_limits();

drop trigger if exists enforce_venue_update_rules on public.venues;
create trigger enforce_venue_update_rules
before update on public.venues
for each row execute function public.enforce_venue_update_rules();

drop trigger if exists enforce_report_insert_limits on public.reports;
create trigger enforce_report_insert_limits
before insert on public.reports
for each row execute function public.enforce_report_insert_limits();

alter table public.teams enable row level security;
alter table public.profiles enable row level security;
alter table public.admin_users enable row level security;
alter table public.matches enable row level security;
alter table public.venues enable row level security;
alter table public.venue_matches enable row level security;
alter table public.votes enable row level security;
alter table public.reports enable row level security;

-- No admin_users policies: deny all client access. Manage by SQL editor or service role.

drop policy if exists "teams are readable by everyone" on public.teams;
create policy "teams are readable by everyone"
on public.teams for select
to anon, authenticated
using (true);

drop policy if exists "matches are readable by everyone" on public.matches;
create policy "matches are readable by everyone"
on public.matches for select
to anon, authenticated
using (true);

drop policy if exists "profiles can select own row" on public.profiles;
create policy "profiles can select own row"
on public.profiles for select
to authenticated
using (id = (select auth.uid()));

drop policy if exists "profiles can insert own row" on public.profiles;
create policy "profiles can insert own row"
on public.profiles for insert
to authenticated
with check (id = (select auth.uid()));

drop policy if exists "profiles can update own row" on public.profiles;
create policy "profiles can update own row"
on public.profiles for update
to authenticated
using (id = (select auth.uid()))
with check (id = (select auth.uid()));

drop policy if exists "approved venues are readable by everyone" on public.venues;
create policy "approved venues are readable by everyone"
on public.venues for select
to anon, authenticated
using (status = 'approved');

drop policy if exists "venue owners can select their venues" on public.venues;
create policy "venue owners can select their venues"
on public.venues for select
to authenticated
using (created_by = (select auth.uid()));

drop policy if exists "admins can select all venues" on public.venues;
create policy "admins can select all venues"
on public.venues for select
to authenticated
using ((select public.is_admin()));

drop policy if exists "authenticated users can submit pending venues" on public.venues;
create policy "authenticated users can submit pending venues"
on public.venues for insert
to authenticated
with check (created_by = (select auth.uid()) and status = 'pending');

drop policy if exists "venue owners can update pending venues" on public.venues;
create policy "venue owners can update pending venues"
on public.venues for update
to authenticated
using (created_by = (select auth.uid()) and status = 'pending')
with check (created_by = (select auth.uid()) and status = 'pending');

drop policy if exists "admins can update all venues" on public.venues;
create policy "admins can update all venues"
on public.venues for update
to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

drop policy if exists "approved venue matches are readable by everyone" on public.venue_matches;
create policy "approved venue matches are readable by everyone"
on public.venue_matches for select
to anon, authenticated
using (
  exists (
    select 1
    from public.venues
    where venues.id = venue_matches.venue_id
      and venues.status = 'approved'
  )
);

drop policy if exists "venue owners can select their venue matches" on public.venue_matches;
create policy "venue owners can select their venue matches"
on public.venue_matches for select
to authenticated
using (
  exists (
    select 1
    from public.venues
    where venues.id = venue_matches.venue_id
      and venues.created_by = (select auth.uid())
  )
);

drop policy if exists "admins can select all venue matches" on public.venue_matches;
create policy "admins can select all venue matches"
on public.venue_matches for select
to authenticated
using ((select public.is_admin()));

drop policy if exists "venue owners can add matches while pending" on public.venue_matches;
create policy "venue owners can add matches while pending"
on public.venue_matches for insert
to authenticated
with check (
  (select public.is_admin())
  or exists (
    select 1
    from public.venues
    where venues.id = venue_matches.venue_id
      and venues.created_by = (select auth.uid())
      and venues.status = 'pending'
  )
);

drop policy if exists "venue owners can remove matches while pending" on public.venue_matches;
create policy "venue owners can remove matches while pending"
on public.venue_matches for delete
to authenticated
using (
  (select public.is_admin())
  or exists (
    select 1
    from public.venues
    where venues.id = venue_matches.venue_id
      and venues.created_by = (select auth.uid())
      and venues.status = 'pending'
  )
);

drop policy if exists "votes are readable by everyone" on public.votes;
drop policy if exists "users can read own votes" on public.votes;
create policy "users can read own votes"
on public.votes for select
to authenticated
using (user_id = (select auth.uid()) or public.is_admin());

drop policy if exists "users can insert own votes" on public.votes;
create policy "users can insert own votes"
on public.votes for insert
to authenticated
with check (
  user_id = (select auth.uid())
  and exists (
    select 1
    from public.venues
    where venues.id = votes.venue_id
      and venues.status = 'approved'
  )
);

drop policy if exists "users can delete own votes" on public.votes;
create policy "users can delete own votes"
on public.votes for delete
to authenticated
using (user_id = (select auth.uid()));

drop policy if exists "users can insert own reports" on public.reports;
create policy "users can insert own reports"
on public.reports for insert
to authenticated
with check (user_id = (select auth.uid()));

drop policy if exists "users can select own reports" on public.reports;
create policy "users can select own reports"
on public.reports for select
to authenticated
using (user_id = (select auth.uid()));

drop policy if exists "admins can select all reports" on public.reports;
create policy "admins can select all reports"
on public.reports for select
to authenticated
using ((select public.is_admin()));

drop policy if exists "admins can update reports" on public.reports;
create policy "admins can update reports"
on public.reports for update
to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'venue-photos',
  'venue-photos',
  true,
  5242880,
  array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update
set
  name = excluded.name,
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "venue photos are publicly readable" on storage.objects;
create policy "venue photos are publicly readable"
on storage.objects for select
to anon, authenticated
using (bucket_id = 'venue-photos');

drop policy if exists "users can upload venue photos to own folder" on storage.objects;
create policy "users can upload venue photos to own folder"
on storage.objects for insert
to authenticated
with check (
  bucket_id = 'venue-photos'
  and (storage.foldername(name))[1] = (select auth.uid())::text
);

drop policy if exists "users can delete own venue photos or admins can delete any" on storage.objects;
create policy "users can delete own venue photos or admins can delete any"
on storage.objects for delete
to authenticated
using (
  bucket_id = 'venue-photos'
  and (
    owner = (select auth.uid())
    or (select public.is_admin())
  )
);

-- -----------------------------------------------------------------------------
-- Public vote counts. Vote rows themselves are private (own-row RLS above);
-- this owner-rights view intentionally exposes only per-venue aggregates.
-- -----------------------------------------------------------------------------
create or replace view public.venue_vote_counts as
select v.venue_id, count(*)::int as vote_count
from public.votes v
join public.venues ven on ven.id = v.venue_id
where ven.status = 'approved'
group by v.venue_id;

revoke all on public.venue_vote_counts from public;
grant select on public.venue_vote_counts to anon, authenticated, service_role;
